<a href="https://colab.research.google.com/github/82everywin/Board_selfportfolio/blob/master/0__%ED%8C%8C%EC%9D%B4%ED%86%A0%EC%B9%98.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **1. 파이토치**

- Tensorflow 와 함께 머신러닝, 딥러닝에서 가장 널리 사용되는 프레임워크
- 초기에는 Torch라는 이름으로 Lua언어 기반으로 만들어졌으나, 파이썬 기반으로 변겅한 것이 PyTorch
- 뉴욕대학교와 페이스북(메타)이 공동으로 개발하였고, 현재 가장 대중적임 .


In [1]:
import torch
print(torch.__version__)

2.1.0+cu118


### 1-1. 스칼라(Scalar)
- 하나의 상수를 의미

In [2]:
var1= torch.tensor([1])

In [3]:
var1

tensor([1])

In [8]:
var2 = torch.tensor([3.1])

In [9]:
var2

tensor([3.1000])

In [10]:
# 두 스칼라의 사칙연산
print(var1 + var2)
print(var1 - var2)
print(var1 * var2)
print(var1 / var2)

tensor([4.1000])
tensor([-2.1000])
tensor([3.1000])
tensor([0.3226])


### 1-2. 벡터(Vector)
- 상수가 두 개 이상 나열되었을 경우

In [12]:
vec1 = torch.tensor([1,2,3])
vec1

tensor([1, 2, 3])

In [14]:
vec2 =torch.tensor([10,20,30])
vec2

tensor([10, 20, 30])

In [16]:
print(vec1 + vec2)
print(vec1 - vec2)
print(vec1 * vec2)
print(vec1 / vec2)

tensor([11, 22, 33])
tensor([ -9, -18, -27])
tensor([10, 40, 90])
tensor([0.1000, 0.1000, 0.1000])


In [17]:
vec3 = torch.tensor([10,20,30,40])
vec3

tensor([10, 20, 30, 40])

In [18]:
# The size of tensor a (3) must match the size of tensor b (4) at non-singleton dimension 0
# print(vec1 + vec3)
# print(vec1 - vec3)
# print(vec1 * vec3)
# print(vec1 / vec3)

RuntimeError: ignored

## 1-3. 행렬(Matrix)
- 2개 이상의 벡터 값을 가지고 만들어진 값으로 행과 열의 개념을 가진 숫자의 나열

In [20]:
mat1 = torch.tensor([[1,2],[3,4]])
print(mat1)

tensor([[1, 2],
        [3, 4]])


In [21]:
mat2 = torch.tensor([[7,8],[9,10]])
print(mat2)

tensor([[ 7,  8],
        [ 9, 10]])


In [22]:
mat3 = torch.tensor([[7,8,9],[10,11,12]])
print(mat3)

tensor([[ 7,  8,  9],
        [10, 11, 12]])


In [23]:
# 두 행렬의 사칙연산
print(mat1 + mat2)
print(mat1 - mat2)
print(mat1 / mat2)
print(mat1 * mat2)

tensor([[ 8, 10],
        [12, 14]])
tensor([[-6, -6],
        [-6, -6]])
tensor([[0.1429, 0.2500],
        [0.3333, 0.4000]])
tensor([[ 7, 16],
        [27, 40]])


1-4. 텐서(Tensor)
- 다수의 행렬이 모이면 텐서
- 배열이나 행렬과 매우 유사한 특수 자료구조
- 파이토치는 텐서를 사용하여 모델의 입력과 출력, 모델의

In [ ]:
A = torch.tensor([1,2,3],[4,5,6])
B = torch.tensor([10,20,30])

# 브로드 캐스팅을 사용하여 A  와 B 병합


In [24]:
tensor1 = torch.tensor([[1,2],[3,4],[5,6],[7,8]])
print(tensor1)


tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])


In [26]:
tensor2 = torch.tensor([[10,11],[12,13],[14,15],[16,17]])
print(tensor2)

tensor([[10, 11],
        [12, 13],
        [14, 15],
        [16, 17]])


In [27]:
print(tensor1 + tensor2)

tensor([[11, 13],
        [15, 17],
        [19, 21],
        [23, 25]])


In [32]:
print(torch.add(tensor1,tensor2))
print('================================')
print(torch.subtract(tensor1,tensor2))
print('================================')
print(torch.multiply(tensor1,tensor2))
print('================================')
print(torch.divide(tensor1,tensor2))

tensor([[11, 13],
        [15, 17],
        [19, 21],
        [23, 25]])
tensor([[-9, -9],
        [-9, -9],
        [-9, -9],
        [-9, -9]])
tensor([[ 10,  22],
        [ 36,  52],
        [ 70,  90],
        [112, 136]])
tensor([[0.1000, 0.1818],
        [0.2500, 0.3077],
        [0.3571, 0.4000],
        [0.4375, 0.4706]])


In [34]:
# tensor1 에 결과를 다시 전장.
tensor1.add_(tensor2)

tensor([[21, 24],
        [27, 30],
        [33, 36],
        [39, 42]])

### 2. 텐서의 변환


In [38]:
data =[[1,2],[3,4]]

In [37]:
import numpy as np

In [40]:
np_array = np.array(data)
np_array

array([[1, 2],
       [3, 4]])

In [45]:
x_np_1 = torch.as_tensor([[1,2],[3,4]])

In [47]:
# 인덱싱 ? okay
x_np_1[0,0]=100


In [41]:
# as_tensor : ndarray 와 동일한 메모리 주조슬 가리키는 뷰를 만듦
# from_numpy : ndarray 와 동일한 메모리 주조슬 가리키는 뷰를 만듦

x_np_2=  torch.as_tensor(np_array)


In [42]:
print(x_np_2)
x_np_2[0,0]=200
print(x_np_2)
print(np_array)

tensor([[1, 2],
        [3, 4]])
tensor([[200,   2],
        [  3,   4]])
[[200   2]
 [  3   4]]


In [43]:
# 반대로도 확인
print("==================================")
np_array[0,0]= 500
print(x_np_2)
print(np_array)

tensor([[500,   2],
        [  3,   4]])
[[500   2]
 [  3   4]]


In [48]:
np_again = x_np_1.numpy()
print(np_again, type(np_again))

[[100   2]
 [  3   4]] <class 'numpy.ndarray'>


# **3. 파이토치 함수**

In [50]:
a = torch.ones(2,3)
print(a)

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [51]:
b= torch.zeros(2,3)
print(b)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [56]:
c = torch.rand(2,3,10)
print(c)

tensor([[[0.9158, 0.3910, 0.1486, 0.2236, 0.3576, 0.4072, 0.1555, 0.6320,
          0.4025, 0.7485],
         [0.3488, 0.0704, 0.0601, 0.2200, 0.1013, 0.2618, 0.1311, 0.3499,
          0.9625, 0.0976],
         [0.4202, 0.5979, 0.0196, 0.6075, 0.8417, 0.2471, 0.2819, 0.1580,
          0.1331, 0.4024]],

        [[0.3416, 0.6164, 0.8204, 0.8343, 0.7676, 0.2855, 0.7857, 0.8534,
          0.8888, 0.4645],
         [0.0769, 0.3403, 0.6817, 0.0288, 0.8272, 0.0634, 0.0034, 0.8322,
          0.4138, 0.4816],
         [0.4013, 0.1288, 0.5392, 0.5983, 0.5594, 0.8046, 0.1098, 0.8978,
          0.8499, 0.9967]]])


In [54]:
e= torch.eye(5)
print(e)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])


In [55]:
f = torch.arange(10)
print(f)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [57]:
g = torch.rand(2,3)
print(g)

tensor([[0.1920, 0.3954, 0.6059],
        [0.0029, 0.1968, 0.0570]])


In [58]:
# 평균이 0이고, 표준편차가 1
h = torch.randn(2,3)
print(h)

tensor([[-0.8975, -0.4760, -0.4703],
        [-0.2697,  0.6173,  1.5083]])


In [61]:
i = torch.arange(16).reshape(2,2,4)
print(i, i.shape)

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7]],

        [[ 8,  9, 10, 11],
         [12, 13, 14, 15]]]) torch.Size([2, 2, 4])


In [64]:
j = i.permute(2,0,1)  # 인덱스로 가져옴 2,2,4 -> 4,2,2
print(j,j.shape)

tensor([[[ 0,  4],
         [ 8, 12]],

        [[ 1,  5],
         [ 9, 13]],

        [[ 2,  6],
         [10, 14]],

        [[ 3,  7],
         [11, 15]]]) torch.Size([4, 2, 2])


# **4. 텐서의 인덱싱과 슬라이싱**

In [66]:
a = torch.arange(1,13).reshape(3,4 )
print(a)

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])


In [67]:
b = torch.arange(1,13,0.5).reshape(6,4)
print(b)

tensor([[ 1.0000,  1.5000,  2.0000,  2.5000],
        [ 3.0000,  3.5000,  4.0000,  4.5000],
        [ 5.0000,  5.5000,  6.0000,  6.5000],
        [ 7.0000,  7.5000,  8.0000,  8.5000],
        [ 9.0000,  9.5000, 10.0000, 10.5000],
        [11.0000, 11.5000, 12.0000, 12.5000]])


In [68]:
print(a[1])

tensor([5, 6, 7, 8])


In [70]:
print(a[1,1])

tensor(6)


In [72]:
print(a[1:-1])

tensor([[5, 6, 7, 8]])


In [74]:
print(a[1,-2])

tensor(7)


# **5. 코랩의 GPU 사용**

- 코랩에서 device 변경하는 방법
  =상단 메뉴 -> 런타임 -> 런타임 유형변겅 -> 하드웨어 가속기를 GPU로 변경-> 저장 -> 다시 시작 및 모두 실행

In [75]:
tensor = torch.rand(3,4)